KUBEADM_CERTSANs: &KUBEADM_CERTSANs
  - "k8s.cloud.local"
  - "192.168.200.190"
  - "k8s.iblog.pro"

KUBEADM_ClusterConfiguration:
    certificatesDir: /etc/kubernetes/pki
    apiServer:
      extraArgs:
        audit-log-format: json
        audit-log-maxage: "7"
        audit-log-maxbackup: "10"
        audit-log-maxsize: "100"
        audit-log-path: /var/log/kube-audit/audit.log
        audit-policy-file: /etc/kubernetes/policies/audit-policy.yaml
      extraVolumes:
      - hostPath: /etc/kubernetes/policies
        mountPath: /etc/kubernetes/policies
        name: policies
        pathType: DirectoryOrCreate
        readOnly: true
      - hostPath: /var/log/kube-audit
        mountPath: /var/log/kube-audit
        name: logs
        pathType: DirectoryOrCreate
      timeoutForControlPlane: 4m0s
      certSANs: *KUBEADM_CERTSANs
    controllerManager:
      extraArgs:
        bind-address: 0.0.0.0
        node-cidr-mask-size-ipv4: "24"
    etcd:
      local:
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381
    scheduler:
      extraArgs:
        bind-address: 0.0.0.0
    dns: {}

KubeletConfiguration:
    registerNode: true
    cgroupDriver: "systemd"
    cgroupsPerQOS: true
    clusterDomain: "cluster.local"
    cpuManagerReconcilePeriod: "0s"
    fileCheckFrequency: "0s"
    healthzBindAddress: "127.0.0.1"
    httpCheckFrequency: "0s"
    imageMinimumGCAge: "0s"
    memorySwap: {}
    nodeStatusReportFrequency: "20s"
    nodeStatusUpdateFrequency: "30s"
    resolvConf: "/run/systemd/resolve/resolv.conf"
    runtimeRequestTimeout: "0s"
    evictionPressureTransitionPeriod: "5m"
    evictionMaxPodGracePeriod: 300
    memoryThrottlingFactor: 0.9
    podsPerCore: 5
    maxPods: 20
    containerLogMaxSize: "50Mi"
    containerLogMaxFiles: 5
    maxParallelImagePulls: 5
    podPidsLimit: 4096
    maxOpenFiles: 1000000
    shutdownGracePeriod: "15s"
    shutdownGracePeriodCriticalPods: "5s"
    streamingConnectionIdleTimeout: "0s"
    syncFrequency: "0s"
    volumeStatsAggPeriod: "0s"
    kubeAPIQPS: 50
    kubeAPIBurst: 100
    rotateCertificates: true
    serverTLSBootstrap: false
    serializeImagePulls: false
    tlsMinVersion: "VersionTLS12"
    imageGCHighThresholdPercent: 55
    imageGCLowThresholdPercent: 50
    kubeletCgroups: /kubelet.slice
    authentication:
        anonymous:
            enabled: false
        webhook:
            cacheTTL: "0s"
            enabled: true
    authorization:
        mode: "Webhook"
        webhook:
          cacheAuthorizedTTL:   "0s"
          cacheUnauthorizedTTL: "0s"
    logging:
      flushFrequency: 0
      options:
        json:
            infoBufferSize:  0
      verbosity:  0
    tlsCipherSuites:
      - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
      - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
    allowedUnsafeSysctls:
      - "net.core.somaxconn"
    systemReserved:
      cpu: 500m
      memory: 1000Mi
      ephemeral-storage: "1Gi"
    kubeReserved:
      cpu: 500m
      memory: 500Mi
      ephemeral-storage: 3Gi
    evictionHard:
      "memory.available":   "500Mi"
      "nodefs.available":   "20%"
      "nodefs.inodesFree":  "10%"
      "imagefs.available":  "25%"
      "imagefs.inodesFree": "15%"
    evictionMinimumReclaim:
      memory.available: "0Mi"
      nodefs.available: "500Mi"
      imagefs.available: "2Gi"
    evictionSoft:
      "memory.available":   "500Mi"
      "nodefs.available":   "25%"
      "nodefs.inodesFree":  "15%"
      "imagefs.available":  "30%"
      "imagefs.inodesFree": "25%"
    evictionSoftGracePeriod:
      "memory.available":   "2m30s"
      "nodefs.available":   "2m30s"
      "nodefs.inodesFree":  "2m30s"
      "imagefs.available":  "2m30s"
      "imagefs.inodesFree": "2m30s"

KubeProxyConfiguration:
    mode: ipvs
    metricsBindAddress: 0.0.0.0:10249

kubernetes_pki:
  - /etc/kubernetes/pki/sa.pub
  - /etc/kubernetes/pki/sa.key
  - /etc/kubernetes/pki/etcd/ca.key
  - /etc/kubernetes/pki/etcd/ca.crt
  - /etc/kubernetes/pki/front-proxy-ca.crt
  - /etc/kubernetes/pki/apiserver-etcd-client.crt
  - /etc/kubernetes/pki/apiserver-etcd-client.key
  - /etc/kubernetes/pki/ca.key
  - /etc/kubernetes/pki/ca.crt
  - /etc/kubernetes/pki/front-proxy-ca.key


