CERMANAGER:
    cainjector_image: "harbor.iblog.pro/quayio/jetstack/cert-manager-cainjector:v1.14.3"
    controller_image: "harbor.iblog.pro/quayio/jetstack/cert-manager-controller:v1.14.3"
    webhook_image: "harbor.iblog.pro/quayio/jetstack/cert-manager-webhook:v1.14.3"
    acme_image: quay.io/jetstack/cert-manager-acmesolver:v1.14.3

METRICSERVER:
    image: harbor.iblog.pro/registryk8sio/metrics-server/metrics-server:v0.6.4

