---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internet2
  namespace: metallb-system
spec:
  # Production services will go here. Public IPs are expensive, so we leased
  # just 4 of them.
  addresses:
  - 11.0.11.2/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: coredns-kube
  namespace: metallb-system
spec:
  # Production services will go here. Public IPs are expensive, so we leased
  # just 4 of them.
  addresses:
  - 11.0.11.22/32
