- hosts: kubernetes
  become: true
  port: 22
  gather_facts: True
  roles:
    - role: node-systemd-timesyncd
      vars:
        system_timezone: Etc/UTC
        ntp_servers:
          - "0.ru.pool.ntp.org"
          - "1.ru.pool.ntp.org"
          - "2.ru.pool.ntp.org"
          - "3.ru.pool.ntp.org"
        ntp_fallback_servers:
          - "0.ru.pool.ntp.org"
          - "1.ru.pool.ntp.org"
          - "2.ru.pool.ntp.org"
          - "3.ru.pool.ntp.org"

- hosts: kubernetes
  port: 22
  gather_facts: True
  roles:
    - role: node-update-off
      become: yes

