---
- name: Post INIT Stage 50
  hosts: bootstrap
  pre_tasks:
    - name: Include all vars files.
      ansible.builtin.include_vars:
        dir: vars
  tasks:
  - block:
     - import_tasks: playbooks/post-init-kube-050.yaml
    when:
     - DEPLOY_HELM|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-052.yaml

  - block:
     - import_tasks: playbooks/post-init-kube-054.yaml
    when:
     - DEPLOY_PriorityClass|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-051.1.yaml
    when:
     - DEPLOY_CNI_CILIUM|bool == true
     - CNI_CILIUM_MULTICLASTER|bool == false

  - block:
     - import_tasks: playbooks/post-init-kube-051.2.yaml
    when:
     - DEPLOY_CNI_CILIUM|bool == true
     - CNI_CILIUM_MULTICLASTER|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-060.yaml
    when:
     - DEPLOY_CNI_ANTREA|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-061.yaml
    when:
     - DEPLOY_CNI_KUBEOVN|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-062.yaml
    when:
     - DEPLOY_CNI_CALICO|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-063.yaml
    when:
     - DEPLOY_TETRAGON|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-064.yaml
    when:
     - DEPLOY_KYVERNO|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-065.yaml
    when:
     - DEPLOY_ARGOCD|bool == true


  - block:
     - import_tasks: playbooks/post-init-kube-053.yaml
    when:
     - DEPLOY_CSI_NFS|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-059.yaml
    when:
     - DEPLOY_NFS_HELM|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-055.yaml
    when:
     - DEPLOY_METRICSERVER|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-056.yaml
    when:
     - DEPLOY_CERMANAGER|bool == true


  - block:
     - import_tasks: playbooks/post-init-kube-057.yaml
    when:
     - DEPLOY_METALLB|bool == true

  - block:
     - import_tasks: playbooks/post-init-kube-058.yaml
    when:
     - DEPLOY_Nginx_Ingress|bool == true


