apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config13
  namespace: test-kube-0
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
  PGDATA: /var/lib/postgresql/data/pgdata
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim13
  namespace: test-kube-0
  labels:
    app: postgres13
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres13
  namespace: test-kube-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres13
  template:
    metadata:
      labels:
        app: postgres13
    spec:
      containers:
        - name: postgres13
          image: docker.io/postgres:13
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config13
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb13
      volumes:
        - name: postgredb13
          persistentVolumeClaim:
            claimName: postgres-pv-claim13
