apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config13v2
  namespace: test-kube-0
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
  PGDATA: /var/lib/postgresql/data/pgdata
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: postgres13
  namespace: test-kube-0
spec:
  replicas: 5
  serviceName: "postgres13"
  selector:
    matchLabels:
      app: postgres13
  template:
    metadata:
      labels:
        app: postgres13
    spec:
      containers:
        - name: postgres13
          image: docker.io/postgres:13
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config13v2
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb13v2
  volumeClaimTemplates:
  - metadata:
      name: postgredb13v2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: managed-nfs-storage
