---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyverno-test-07-claim3
  namespace: test-kube-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web10
  namespace: test-kube-0
  labels:
    opa: antiaffinity-all-nodes
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 2
  template:
    metadata:
      labels:
        opa: antiaffinity-all-nodes
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: docker.io/nginx:1.20
        ports:
        - containerPort: 80
          name: web10
        resources:
          limits:
            cpu: "0.2"
            memory: "300Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        volumeMounts:
          - name: pvc-sample
            mountPath: /var/log/nfs
      volumes:
        - name: pvc-sample
          persistentVolumeClaim:
            claimName: kyverno-test-07-claim3
