
  - block:
    - name: Creates directory
      file:
        path: /etc/kubernetes/pki/etcd
        state: directory
        owner: root
        group: root
        mode: 0775
        recurse: yes
    - name: ansible copy file from local to remote.
      ansible.builtin.copy:
        src: /tmp/deploy/{{ item }}
        dest: "{{ item }}"
      loop: "{{ kubernetes_pki }}"
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
