
  - block:
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Copy ubuntu-sources.list.j2
      template:
        src: "ubuntu-sources.list.j2"
        dest: "/etc/apt/sources.list"
        owner: "root"
        group: "root"
        mode: '0644'
      when: ansible_distribution == 'Ubuntu'

    - name: Copy debian-sources.list.j2
      template:
        src: "debian-sources.list.j2"
        dest: "/etc/apt/sources.list"
        owner: "root"
        group: "root"
        mode: '0644'
      when: ansible_distribution == 'Debian'

    - name: Install a list of packages
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - locales
          - mc

    - name: Run patch /etc/locale.gen
      ansible.builtin.shell: sed -i -e "s/# ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/" /etc/locale.gen
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines


    - name: Run patch /etc/locale.gen
      ansible.builtin.shell: sed -i -e "s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/" /etc/locale.gen
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines


    - name: Run dpkg-reconfigure --frontend=noninteractive locales
      ansible.builtin.shell: dpkg-reconfigure --frontend=noninteractive locales
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run echo "nameserver {{ NAMESERVER }}" >>/etc/resolv.conf
      ansible.builtin.shell: echo "nameserver {{ NAMESERVER }}" >>/etc/resolv.conf
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run dpkg-reconfigure --frontend=noninteractive locales
      ansible.builtin.shell: dpkg-reconfigure --frontend=noninteractive locales
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines


    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400


    - name: Install a list of packages
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - locales-all
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - nfs-common

    - name: Copy modules-load.d-containerd.conf
      template:
        src: "modules-load.d-containerd.conf.j2"
        dest: "/etc/modules-load.d/containerd.conf"
        owner: "root"
        group: "root"
        mode: '0644'

    - name: Run modprobe overlay
      ansible.builtin.shell: modprobe overlay
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run modprobe br_netfilter
      ansible.builtin.shell: modprobe br_netfilter
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines


    - name: Copy modules-load.d-containerd.conf
      template:
        src: "sysctl-99-kubernetes-cri.conf.j2"
        dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
        owner: "root"
        group: "root"
        mode: '0644'

    - name: Copy modules-load.d-containerd.conf
      template:
        src: "security-limits.conf.j2"
        dest: "/etc/security/limits.conf"
        owner: "root"
        group: "root"
        mode: '0644'


    - name: Run sysctl --system
      ansible.builtin.shell: sysctl --system
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Copy IMAGES/kubeadm.amd64.{{kube_version}}
      ansible.builtin.copy:
        src: IMAGES/crictl-{{crictl_version}}-linux-amd64.tar.gz
        dest: /tmp
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Run tar Cxzvf /usr/local/bin /tmp/crictl-{{crictl_version}}-linux-amd64.tar.gz
      ansible.builtin.shell: tar Cxzvf /usr/local/bin /tmp/crictl-{{crictl_version}}-linux-amd64.tar.gz
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run chmod +x /usr/local/bin/crictl
      ansible.builtin.shell: chmod +x /usr/local/bin/crictl
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines


    - name: Copy IMAGES/kubeadm.amd64.{{kube_version}}
      ansible.builtin.copy:
        src: IMAGES/containerd-{{ containerd_version }}-linux-amd64.tar.gz
        dest: /tmp
        owner: root
        group: root
        mode: '0777'
        backup: yes

    - name: Run tar Cxzvf /usr/local ./IMAGES/containerd-{{ containerd_version }}-linux-amd64.tar.gz
      ansible.builtin.shell: tar Cxzvf /usr/local /tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Copy containerd.service
      ansible.builtin.copy:
        src: containerd.service
        dest: /etc/systemd/system/containerd.service
        owner: root
        group: root
        mode: '0777'
        backup: yes

    - name: Copy containerd.service
      ansible.builtin.copy:
        src: IMAGES/runc.{{image_arch}}
        dest: /usr/local/sbin/runc
        owner: root
        group: root
        mode: '0777'
        backup: yes

    - name: Run tar Cxzvf /usr/local /tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz
      ansible.builtin.shell: tar Cxzvf /usr/local /tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines


    - name: Run mkdir -p /opt/cni/bin
      ansible.builtin.shell: mkdir -p /opt/cni/bin
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Copy containerd.service
      ansible.builtin.copy:
        src: IMAGES/cni-plugins-linux-{{image_arch}}-v{{cni_version}}.tgz
        dest: /tmp
        owner: root
        group: root
        mode: '0777'
        backup: yes

    - name: Run tar Cxzvf /opt/cni/bin /tmp/cni-plugins-linux-{{image_arch}}-v{{cni_version}}.tgz
      ansible.builtin.shell: tar Cxzvf /opt/cni/bin /tmp/cni-plugins-linux-{{image_arch}}-v{{cni_version}}.tgz
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run mkdir -p /etc/containerd
      ansible.builtin.shell: mkdir -p /etc/containerd
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run chown -R root:root /opt/cni/bin
      ansible.builtin.shell: chown -R root:root /opt/cni/bin
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run containerd config default | sudo tee /etc/containerd/config.toml
      ansible.builtin.shell: containerd config default | sudo tee /etc/containerd/config.toml
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run sed -i -e "s|            SystemdCgroup = false|            SystemdCgroup = true|" /etc/containerd/config.toml
      ansible.builtin.shell: sed -i -e "s|            SystemdCgroup = false|            SystemdCgroup = true|" /etc/containerd/config.toml
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run sed -i -e 's|    sandbox_image = "registry.k8s.io/pause:3.8"|    sandbox_image = "harbor.iblog.pro/registry.k8s.io/pause:3.10"|' /etc/containerd/config.toml
      ansible.builtin.shell: sed -i -e 's|    sandbox_image = "registry.k8s.io/pause:3.8"|    sandbox_image = "harbor.iblog.pro/registry.k8s.io/pause:3.10"|' /etc/containerd/config.toml
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run sed -i -e 's|      config_path = ""|      config_path = "/etc/containerd/certs.d"|' /etc/containerd/config.toml
      ansible.builtin.shell: sed -i -e 's|      config_path = ""|      config_path = "/etc/containerd/certs.d"|' /etc/containerd/config.toml
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Copy containerd.service
      ansible.builtin.copy:
        src: CONTAINERED.CONF/certs.d
        dest: /etc/containerd
        owner: root
        group: root
        mode: '666'
        backup: yes

    - name: systemd daemon_reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable service containerd and ensure
      ansible.builtin.systemd:
        name: containerd
        enabled: true

    - name: Start service containerd
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: true


    - name: Run cat /etc/containerd/config.toml | grep SystemdCgroup
      ansible.builtin.shell: cat /etc/containerd/config.toml | grep SystemdCgroup
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines


    - name: Run ctr images pull {{TEST_HARBOR}}
      ansible.builtin.shell: ctr images pull {{TEST_HARBOR}}
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run ctr images ls
      ansible.builtin.shell: ctr images ls
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Copy etc-crictl.yaml.j2
      template:
        src: "etc-crictl.yaml.j2"
        dest: "/etc/crictl.yaml"
        owner: "root"
        group: "root"
        mode: '0644'

    - name: Copy IMAGES/kubeadm.amd64.{{kube_version}}
      ansible.builtin.copy:
        src: IMAGES/kubeadm.amd64.{{kube_version}}
        dest: /usr/bin/kubeadm
        owner: root
        group: root
        mode: '0777'
        backup: yes

    - name: Copy IMAGES/kubectl.amd64.{{kube_version}}
      ansible.builtin.copy:
        src: IMAGES/kubectl.amd64.{{kube_version}}
        dest: /usr/bin/kubectl
        owner: root
        group: root
        mode: '0777'
        backup: yes

    - name: Copy IMAGES/kubelet.amd64.{{kube_version}}
      ansible.builtin.copy:
        src: IMAGES/kubelet.amd64.{{kube_version}}
        dest: /usr/bin/kubelet
        owner: root
        group: root
        mode: '0777'
        backup: yes

    - name: Run mkdir -p /etc/kubernetes
      ansible.builtin.shell: mkdir -p /etc/kubernetes
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Install a list of packages
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - iptables
          - iproute2
          - socat
          - util-linux
          - mount
          - ebtables
          - ethtool
          - conntrack

    - name: Run mkdir -p /etc/systemd/system/kubelet.service.d/
      ansible.builtin.shell: mkdir -p /etc/systemd/system/kubelet.service.d/
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines


    - name: Copy kubelet.service.d-10-kubeadm.conf.j2
      template:
        src: "kubelet.service.d-10-kubeadm.conf.j2"
        dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
        owner: "root"
        group: "root"
        mode: '0644'

    - name: Copy kubelet.service.j2
      template:
        src: "kubelet.service.j2"
        dest: "/lib/systemd/system/kubelet.service"
        owner: "root"
        group: "root"
        mode: '0644'

    - name: systemd daemon_reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable service kubelet and ensure
      ansible.builtin.systemd:
        name: kubelet
        enabled: true

    - name: Start service kubelet
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: true

    - name: Run kubeadm config images pull --image-repository {{ k8s_regestry }} --kubernetes-version {{ kube_version }}
      ansible.builtin.shell: kubeadm config images pull --image-repository {{ k8s_regestry }} --kubernetes-version {{ kube_version }}
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run mkdir -p /etc/kubernetes/manifests
      ansible.builtin.shell: mkdir -p /etc/kubernetes/manifestsmkdir -p /etc/kubernetes/manifests
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
