
  - block:

     - name: Run task echo .......
       ansible.builtin.shell: echo "host is {{item}}"
       args:
         executable: /bin/bash
       with_items:  "{{ groups['master'] }}"
       register: logs

     - debug: msg="item.item={{item.item}}, item.stdout={{item.stdout}}, item.changed={{item.changed}}"
       with_items: "{{logs.results}}"


     - name: Run task kubectl label node........
       ansible.builtin.shell: kubectl label node {{item}} node-role.kubernetes.io/master=
       args:
         executable: /bin/bash
       with_items:  "{{ groups['master'] }}"
       register: logs

     - debug: msg="item.item={{item.item}}, item.stdout={{item.stdout}}, item.changed={{item.changed}}"
       with_items: "{{logs.results}}"

     - name: Run kubectl taint nodes --all node-role.kubernetes.io/master-
       ansible.builtin.shell: kubectl taint nodes --all node-role.kubernetes.io/master-
       args:
         executable: /bin/bash
       register: logs
       failed_when: "'FAILED' in command_result.stderr"
       ignore_errors: true
     - debug: var=logs.stdout_lines




     - name: Run task kubectl label node........
       ansible.builtin.shell: kubectl label node {{item}} node-role.kubernetes.io/worker=
       args:
         executable: /bin/bash
       with_items:  "{{ groups['worker'] }}"
       register: logs

     - debug: msg="item.item={{item.item}}, item.stdout={{item.stdout}}, item.changed={{item.changed}}"
       with_items: "{{logs.results}}"

     - name: Run task kubectl label node........
       ansible.builtin.shell: kubectl label node {{item}} ingress=on
       args:
         executable: /bin/bash
       with_items:  "{{ groups['worker'] }}"
       register: logs

     - debug: msg="item.item={{item.item}}, item.stdout={{item.stdout}}, item.changed={{item.changed}}"
       with_items: "{{logs.results}}"


     - name: Run task kubectl label node katacontainers.io/gvisor=on
       ansible.builtin.shell: kubectl label node {{item}} katacontainers.io/gvisor=on
       args:
         executable: /bin/bash
       with_items:  "{{ groups['worker'] }}"
       register: logs

     - debug: msg="item.item={{item.item}}, item.stdout={{item.stdout}}, item.changed={{item.changed}}"
       with_items: "{{logs.results}}"


     - name: Run task kubectl label node katacontainers.io/kata-runtime=on
       ansible.builtin.shell: kubectl label node {{item}} katacontainers.io/kata-runtime=on
       args:
         executable: /bin/bash
       with_items:  "{{ groups['worker'] }}"
       register: logs

     - debug: msg="item.item={{item.item}}, item.stdout={{item.stdout}}, item.changed={{item.changed}}"
       with_items: "{{logs.results}}"

