
  - block:
    - name: install keepalived
      package:
        name: keepalived
        state: present
      when:
        - inventory_hostname in groups['master']
    - name: Copy check_apiserver.sh
      template:
        src: "check_apiserver.sh.j2"
        dest: /etc/keepalived/check_apiserver.sh
        mode: '0777'
      when:
        - inventory_hostname in groups['master']
    - name: Copy keepalived.conf
      template:
        src: "keepalived.conf.j2"
        dest: /etc/keepalived/keepalived.conf
        mode: '0644'
      when:
        - inventory_hostname in groups['master']
    - name: Start service keepalived
      ansible.builtin.systemd:
        name: keepalived
        state: reloaded
        enabled: true
      when:
        - inventory_hostname in groups['master']
    - name: Start service keepalived, if not started
      service:
        name: keepalived
        state: started
        enabled: yes
      when:
        - inventory_hostname in groups['master']
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
