
  - block:

    - name: Run mkdir -p /etc/kubernetes/kubeadm/patches/
      ansible.builtin.shell: mkdir -p /etc/kubernetes/kubeadm/patches/
      args:
        executable: /bin/bash
      register: logs
      when:
      - inventory_hostname in groups['master']
      - KUBEADM_Patch_init== "yes"
    - debug: var=logs.stdout_lines
      when:
      - inventory_hostname in groups['master']
      - KUBEADM_Patch_init== "yes"

    - name: Copy Patch kube-apiserver.yaml
      template:
        src: "patch-kube-apiserver.yaml.{{KUBEADM_CONFIG_VERSION}}.j2"
        dest: /etc/kubernetes/kubeadm/patches/kube-apiserver.yaml
        mode: '0644'
      when:
      - inventory_hostname in groups['master']
      - KUBEADM_Patch_init== "yes"

    - name: Copy Patch kube-controller-manager.yaml
      template:
        src: "patch-kube-controller-manager.yaml.{{KUBEADM_CONFIG_VERSION}}.j2"
        dest: /etc/kubernetes/kubeadm/patches/kube-controller-manager.yaml
        mode: '0644'
      when:
      - inventory_hostname in groups['master']
      - KUBEADM_Patch_init== "yes"

    - name: Copy Patch kube-scheduler.yaml
      template:
        src: "patch-kube-scheduler.yaml.{{KUBEADM_CONFIG_VERSION}}.j2"
        dest: /etc/kubernetes/kubeadm/patches/kube-scheduler.yaml
        mode: '0644'
      when:
      - inventory_hostname in groups['master']
      - KUBEADM_Patch_init== "yes"

    - name: Copy Patch corednsdeployment.yaml
      template:
        src: "patch-corednsdeployment.yaml.{{KUBEADM_CONFIG_VERSION}}.j2"
        dest: /etc/kubernetes/kubeadm/patches/corednsdeployment.yaml
        mode: '0644'
      when:
      - inventory_hostname in groups['master']
      - KUBEADM_Patch_init== "yes"

    - name: Copy Patch etcd.yaml
      template:
        src: "patch-etcd.yaml.{{KUBEADM_CONFIG_VERSION}}.j2"
        dest: /etc/kubernetes/kubeadm/patches/etcd.yaml
        mode: '0644'
      when:
      - inventory_hostname in groups['master']
      - KUBEADM_Patch_init== "yes"


    - name: Run mkdir -p /etc/kubernetes/policies/
      ansible.builtin.shell: mkdir -p /etc/kubernetes/policies/
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines


    - name: Run mkdir -p /var/log/kube-audit
      ansible.builtin.shell: mkdir -p /var/log/kube-audit
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run copy audit-policy.yaml /etc/kubernetes/policies/
      template:
        src: "audit-policy.yaml.j2"
        dest: /etc/kubernetes/policies/audit-policy.yaml
        mode: '0644'

    - name: Copy kubeadm.yml
      template:
        src: "kubeadm.yml.{{KUBEADM_CONFIG_VERSION}}.j2"
        dest: /root/kubeadm.yml
        mode: '0644'

    - name: Run cat  kubeadm.yml
      ansible.builtin.shell: cat /root/kubeadm.yml
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run cat  kubeadm.yml
      ansible.builtin.shell: cat /root/kubeadm.yml
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run cat  mkdir /sys/fs/cgroup/kubepod.cluster.slice/
      ansible.builtin.shell: if [ ! -d "/sys/fs/cgroup/kubepod.cluster.slice/" ]; then     echo "Directory /sys/fs/cgroup/kubepod.cluster.slice/ DOES NOT exists.";     mkdir /sys/fs/cgroup/kubepod.cluster.slice/ || throw 18380; fi
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run kubeadm config migrate --old-config kubeadm.yml  --new-config kubeadm.v3.yml
      ansible.builtin.shell: cd /root; kubeadm config migrate --old-config kubeadm.yml  --new-config kubeadm.v3.yml
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run kubeadm init --config=./kubeadm.yml
      ansible.builtin.shell: cd /root; kubeadm init --config=/root/kubeadm.yml
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
