
  - block:
    - name: Recursively remove directory /root/.kube
      ansible.builtin.file:
        path: /root/.kube
        state: absent

    - name: Run mkdir -p /root/.kube
      ansible.builtin.shell: mkdir -p /root/.kube
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run cp -i /etc/kubernetes/admin.conf /root/.kube/config
      ansible.builtin.shell: cp -i /etc/kubernetes/admin.conf /root/.kube/config
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run chown 0:0 /root/.kube/config
      ansible.builtin.shell: chown 0:0 /root/.kube/config
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run mkdir -p /root/.kube
      ansible.builtin.shell: mkdir -p /root/.kube
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run kubectl get nodes,pod -A -o wide
      ansible.builtin.shell: kubectl get nodes,pod -A -o wide
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run kubectl taint nodes --all node-role.kubernetes.io/master-
      ansible.builtin.shell: kubectl taint nodes --all node-role.kubernetes.io/master-
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run sleep 20 second
      ansible.builtin.shell: cd /root; sleep 20
      args:
        executable: /bin/bash
      register: logs
      when:
      - KUBERNETES_COREDNS_ENABLE_PATCH|bool == true
    - debug: var=logs.stdout_lines
      when:
      - KUBERNETES_COREDNS_ENABLE_PATCH|bool == true

    - name: Run kubectl patch coredns
      ansible.builtin.shell: |
          kubectl patch  -n kube-system deployment coredns --type='merge' -p '{"spec":{"replicas": 3, "template":{"spec": {"containers":[{"name":"coredns", "image": "{{HABOR_MAIN}}/coredns:v{{KUBERNETES_COREDNS_VERSION}}", "resources": {"limits":{"cpu": "200m", "memory": "170Mi"}, "requests": {"cpu": "100m", "memory": "70Mi"}} }] } }}}'
      args:
        executable: /bin/bash
      register: logs
      when:
      - KUBERNETES_COREDNS_ENABLE_PATCH|bool == true
    - debug: var=logs.stdout_lines
      when:
      - KUBERNETES_COREDNS_ENABLE_PATCH|bool == true

    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
