    - name: Deploy cilium w/o cluster mesh
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      community.kubernetes.helm:
        name: cloudstack-cilium
        chart_ref: "{{CNI.CILIUM.chart_ref}}"
        release_state: "{{CNI.CILIUM.release_state}}"
        update_repo_cache: "{{CNI.CILIUM.update_repo_cache}}"
        release_namespace: "{{CNI.CILIUM.release_namespace}}"
        create_namespace: "{{CNI.CILIUM.create_namespace}}"
        chart_version: "{{CNI.CILIUM.chart_version}}"
        values:
          kubeProxyReplacement: "{{CNI.CILIUM.cilium_kubeProxyReplacement}}"
          clusterDomain: "KUBERNETES_clusterDomain"
          k8sServiceHost: "{{KUBERNETES_VIP}}"
          k8sServicePort: 6443
          rollOutCiliumPods: true
          tunnelProtocol: "{{CNI.CILIUM.cilium_tunnelProtocol}}"
          l7Proxy: "{{CNI.CILIUM.cilium_l7Proxy}}"
          localRedirectPolicy: false
          bpf:
            masquerade: true
          ingressController:
            enabled: "{{CNI.CILIUM.cilium_ingressController}}"
            loadbalancerMode: "{{CNI.CILIUM.cilium_ingressController_loadbalancerMode}}"
          hostFirewall:
            enabled: false
          hostPort:
            enabled: false
          socketLB:
            enabled: false
          nodePort:
            enabled: "{{CNI.CILIUM.cilium_nodePort}}"
          egressGateway:
              enabled: "{{CNI.CILIUM.cilium_egressGateway}}"
          ipam:
              operator:
                  clusterPoolIPv4PodCIDRList: "{{CNI.CILIUM.clusterPoolIPv4PodCIDRList}}"
#                  clusterPoolIPv4MaskSize: "{{CNI.CILIUM.clusterPoolIPv4MaskSize}}"
# fatal: [node130]: FAILED! => {"changed": false, "command": "/usr/bin/helm --version=1.16.1 upgrade -i --reset-values --create-namespace -f=/tmp/tmp34z_scqh.yml cloudstack-cilium cloudstack/cilium", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):\ncilium:\n- ipam.operator.clusterPoolIPv4MaskSize: Invalid type. Expected: integer, given: string\n\n", "stderr": "Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):\ncilium:\n- ipam.operator.clusterPoolIPv4MaskSize: Invalid type. Expected: integer, given: string\n\n", "stderr_lines": ["Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):", "cilium:", "- ipam.operator.clusterPoolIPv4MaskSize: Invalid type. Expected: integer, given: string", ""], "stdout": "", "stdout_lines": []}
          debug:
            enabled: false
          monitor:
            enabled: false
          image:
            repository: "{{CNI.CILIUM.cilium_repository}}"
          certgen:
            image:
              repository: "{{CNI.CILIUM.certgen_repository}}"
          resources:
             limits:
               cpu: 1000m
               memory: 1Gi
             requests:
               cpu: 100m
               memory: 512Mi
          hubble:
            enabled: "{{CNI.CILIUM.cilium_hubble}}"
            relay:
              enabled: "{{CNI.CILIUM.cilium_hubble_relay}}"
              image:
                repository: "{{CNI.CILIUM.hubble_relay_repository}}"
              resources:
                 limits:
                   cpu: 250m
                   memory: 256Mi
                 requests:
                   cpu: 100m
                   memory: 128Mi
              replicas: 2
            ui:
              enabled: "{{CNI.CILIUM.cilium_hubble_ui}}"
              frontend:
                image:
                  repository: "{{CNI.CILIUM.hubble_ui_repository}}"
                resources:
                   limits:
                     cpu: 300m
                     memory: 256Mi
                   requests:
                     cpu: 100m
                     memory: 128Mi
              backend:
                image:
                  repository: "{{CNI.CILIUM.hubble_ui_backend_repository}}"
                resources:
                   limits:
                     cpu: 300m
                     memory: 256Mi
                   requests:
                     cpu: 100m
                     memory: 128Mi
          etcd:
            enabled: false
            image:
              repository: "{{CNI.CILIUM.cilium_etcd_operator_repository}}"
          operator:
            enabled: true
            image:
              repository: "{{CNI.CILIUM.operator_repository}}"
            podDisruptionBudget:
              enabled: true
#              minAvailable: 1
#              maxUnavailable: 1
            resources:
               limits:
                 cpu: 1000m
                 memory: 1Gi
               requests:
                 cpu: 100m
                 memory: 128Mi
          nodeinit:
            enabled: false
            image:
              repository: "{{CNI.CILIUM.startup_script_repository}}"
            resources:
              requests:
                 cpu: 100m
                 memory: 100Mi
              limits:
                 cpu: 1000m
                 memory: 1Gi
          loadBalancer:
            l7:
              backend: "envoy"
          envoy:
            enabled: "{{CNI.CILIUM.cilium_envoy}}"
            image:
              repository: "{{CNI.CILIUM.cilium_envoy_repository}}"
            resources:
               limits:
                 cpu: 1000m #4000m
                 memory: 1Gi #4Gi
               requests:
                 cpu: 100m
                 memory: 512Mi
          clustermesh:
            useAPIServer: false
            apiserver:
              image:
                repository: "{{CNI.CILIUM.clustermesh_apiserver_repository}}"
            mutual:
              spire:
                enabled: false
                install:
                  enabled: true
                  namespace: cilium-spire
                  existingNamespace: false
                  initImage:
                    repository: "{{CNI.CILIUM.busybox_repository}}"
                  agent:
                    image:
                      repository: "{{CNI.CILIUM.spire_agent_repository}}"
                  server:
                    image:
                      repository: "{{CNI.CILIUM.spire_server_repository}}"
      register: result

    - debug: var=result.stdout_lines

    - name: Sleep 90 second, init CNI
      pause:
        seconds: 90

