
    - name: Deploy CNI Antrea
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      community.kubernetes.helm:
        name: antrea
        chart_ref: "{{CNI.ANTREA.chart_ref}}"
        release_state: "{{CNI.ANTREA.release_state}}"
        update_repo_cache: "{{CNI.ANTREA.update_repo_cache}}"
        release_namespace: "{{CNI.ANTREA.release_namespace}}"
        create_namespace: "{{CNI.ANTREA.create_namespace}}"
        chart_version: "{{CNI.ANTREA.chart_version}}"
        values:
          agentImage:
            repository: "{{CNI.ANTREA.helm_values.agentImage.repository}}"
            pullPolicy: "{{CNI.ANTREA.helm_values.agentImage.pullPolicy}}"
            tag:        "{{CNI.ANTREA.helm_values.agentImage.tag}}"
          controllerImage:
            repository: "{{CNI.ANTREA.helm_values.controllerImage.repository}}"
            pullPolicy: "{{CNI.ANTREA.helm_values.controllerImage.pullPolicy}}"
            tag:        "{{CNI.ANTREA.helm_values.controllerImage.tag}}"
          trafficEncapMode: "encap"
          tunnelType: "geneve"
          trafficEncryptionMode: "none"
          antreaProxy:
            enable: true
            proxyAll: false
            nodePortAddresses: []
            skipServices: []
            proxyLoadBalancerIPs: true
            serviceProxyName: ""
            defaultLoadBalancerMode: "nat"
          nodeIPAM:
            enable: false
            clusterCIDRs: []
            serviceCIDR: ""
            serviceCIDRv6: ""
            nodeCIDRMaskSizeIPv4: 24
            nodeCIDRMaskSizeIPv6: 64


