
    - name: Update repositories cache and install "python3-pip" package
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes

    - name: pip3 install kubernetes
      command: pip3 install kubernetes --break-system-packages
      register: result
    - debug: var=result.stdout_lines

