    - name: Deploy cilium and clustermesh
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      community.kubernetes.helm:
        name: cloudstack-cilium
        chart_ref: "{{CNI.CILIUM.chart_ref}}"
        release_state: "{{CNI.CILIUM.release_state}}"
        update_repo_cache: "{{CNI.CILIUM.update_repo_cache}}"
        release_namespace: "{{CNI.CILIUM.release_namespace}}"
        create_namespace: "{{CNI.CILIUM.create_namespace}}"
        chart_version: "{{CNI.CILIUM.chart_version}}"
        values:
          kubeProxyReplacement: "{{CNI_CILIUM_MULTICLASTER_kubeProxyReplacement}}"
          clusterDomain: "{{CNI_CILIUM_MULTICLASTER_clusterDomain}}"
          k8sServiceHost: "{{KUBERNETES_VIP}}"
          k8sServicePort: 6443
          rollOutCiliumPods: "true"
          tunnelProtocol: "{{CNI_CILIUM_MULTICLASTER_tunnel}}"
          l7Proxy: "{{CNI_CILIUM_MULTICLASTER_l7Proxy}}"
          localRedirectPolicy: "{{CNI_CILIUM_MULTICLASTER_localRedirectPolicy}}"
          cluster:
            name: "{{CNI_CILIUM_MULTICLASTER_cluster_name}}"
            id: "{{CNI_CILIUM_MULTICLASTER_cluster_id}}"
          bpf:
              masquerade: true
          ingressController:
            enabled: "{{CNI_CILIUM_MULTICLASTER_ingressController}}"
          hostFirewall:
            enabled: false
          hostPort:
            enabled: "{{CNI_CILIUM_MULTICLASTER_hostPort}}"
          socketLB:
            enabled: "{{CNI_CILIUM_MULTICLASTER_socketLB}}"
          externalIPs:
            enabled: "{{CNI_CILIUM_MULTICLASTER_externalIPs}}"
          nodePort:
            enabled: "{{CNI_CILIUM_MULTICLASTER_nodePort}}"
          hostServices:
            enabled: "{{CNI_CILIUM_MULTICLASTER_hostServices}}"
          egressGateway:
              enabled: "{{CNI_CILIUM_MULTICLASTER_egressGateway}}"
          ipam:
              operator:
                  clusterPoolIPv4PodCIDRList: "{{CNI.CILIUM.clusterPoolIPv4PodCIDRList}}"
                  clusterPoolIPv4MaskSize: "{{CNI.CILIUM.clusterPoolIPv4MaskSize}}"
          debug:
            enabled: false
          monitor:
            enabled: false
          image:
            repository: "{{CNI.CILIUM.cilium_repository}}"
          certgen:
            image:
              repository: "{{CNI.CILIUM.certgen_repository}}"
          hubble:
            enabled: "{{CNI_CILIUM_MULTICLASTER_hubble}}"
            relay:
              enabled: "{{CNI_CILIUM_MULTICLASTER_hubble_relay}}"
              image:
                repository: "{{CNI.CILIUM.hubble_relay_repository}}"
            ui:
              enabled: "{{CNI_CILIUM_MULTICLASTER_hubble_ui}}"
              frontend:
                image:
                  repository: "{{CNI.CILIUM.hubble_ui_repository}}"
              backend:
                image:
                  repository: "{{CNI.CILIUM.hubble_ui_backend_repository}}"
          envoy:
            enabled: false
            image:
              repository: "{{CNI.CILIUM.cilium_envoy_repository}}"
          etcd:
            enabled: false
            image:
              repository: "{{CNI.CILIUM.cilium_etcd_operator_repository}}"
          operator:
            enabled: true
            image:
              repository: "{{CNI.CILIUM.operator_repository}}"
          nodeinit:
            enabled: "{{CNI_CILIUM_MULTICLASTER_nodeinit}}"
            image:
              repository: "{{CNI.CILIUM.startup_script_repository}}"
          clustermesh:
            useAPIServer: "{{CNI_CILIUM_MULTICLASTER_clustermesh_useAPIServer}}"
            config:
              enabled: "{{CNI_CILIUM_MULTICLASTER_clustermesh_enabled}}"
              domain: "{{CNI_CILIUM_MULTICLASTER_clustermesh_domain}}"
            apiserver:
              replicas: 2
              image:
                repository: "{{CNI.CILIUM.clustermesh_apiserver_repository}}"
          authentication:
            mutual:
              spire:
                enabled: false
                install:
                  enabled: true
                  namespace: cilium-spire
                  existingNamespace: false
                  initImage:
                    repository: "{{CNI.CILIUM.busybox_repository}}"
                  agent:
                    image:
                      repository: "{{CNI.CILIUM.spire_agent_repository}}"
                  server:
                    image:
                      repository: "{{CNI.CILIUM.spire_server_repository}}"
      register: result

    - debug: var=result.stdout_lines

    - name: Sleep 90 second, init CNI
      pause:
        seconds: 90
