
    - name: "Run - kubectl label node -lbeta.kubernetes.io/os=linux kubernetes.io/os=linux --overwrite"
      ansible.builtin.shell: kubectl label node -lbeta.kubernetes.io/os=linux kubernetes.io/os=linux --overwrite
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: "Run - kubectl label node -lnode-role.kubernetes.io/control-plane kube-ovn/role=master --overwrite"
      ansible.builtin.shell: kubectl label node -lnode-role.kubernetes.io/control-plane kube-ovn/role=master --overwrite
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: "Run - kubectl label node -lovn.kubernetes.io/ovs_dp_type!=userspace ovn.kubernetes.io/ovs_dp_type=kernel --overwrite"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      ansible.builtin.shell: kubectl label node -lovn.kubernetes.io/ovs_dp_type!=userspace ovn.kubernetes.io/ovs_dp_type=kernel --overwrite
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Deploy CNI KUBE-OVN
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      community.kubernetes.helm:
        name: kube-ovn
        chart_ref: "{{CNI.KUBEOVN.chart_ref}}"
        release_state: "{{CNI.KUBEOVN.release_state}}"
        update_repo_cache: "{{CNI.KUBEOVN.update_repo_cache}}"
        release_namespace: "{{CNI.KUBEOVN.release_namespace}}"
        # kube-system
        create_namespace: "{{CNI.KUBEOVN.create_namespace}}"
        chart_version: "{{CNI.KUBEOVN.chart_version}}"
        values:
          global:
            registry:
              address: "{{CNI.KUBEOVN.helm_values.global.registry.address}}"
            images:
              kubeovn:
                repository: "{{CNI.KUBEOVN.helm_values.global.images.kubeovn.repository}}"
                dpdkRepository: "{{CNI.KUBEOVN.helm_values.global.images.kubeovn.dpdkRepository}}"
                vpcRepository: "{{CNI.KUBEOVN.helm_values.global.images.kubeovn.vpcRepository}}"
                tag: "{{CNI.KUBEOVN.helm_values.global.images.kubeovn.tag}}"
                support_arm: "{{CNI.KUBEOVN.helm_values.global.images.kubeovn.support_arm}}"
                thirdparty: "{{CNI.KUBEOVN.helm_values.global.images.kubeovn.thirdparty}}"
          replicaCount: 3
          MASTER_NODES: "{{CNI.KUBEOVN.MASTERS}}"
          func:
            ENABLE_LB: "{{CNI.KUBEOVN.helm_values.func.ENABLE_LB}}"
            ENABLE_NP: "{{CNI.KUBEOVN.helm_values.func.ENABLE_NP}}"
            ENABLE_EXTERNAL_VPC: "{{CNI.KUBEOVN.helm_values.func.ENABLE_EXTERNAL_VPC}}"
            HW_OFFLOAD: "{{CNI.KUBEOVN.helm_values.func.HW_OFFLOAD}}"
            ENABLE_LB_SVC: "{{CNI.KUBEOVN.helm_values.func.ENABLE_LB_SVC}}"
            ENABLE_KEEP_VM_IP: "{{CNI.KUBEOVN.helm_values.func.ENABLE_KEEP_VM_IP}}"
            LS_DNAT_MOD_DL_DST: "{{CNI.KUBEOVN.helm_values.func.LS_DNAT_MOD_DL_DST}}"
            LS_CT_SKIP_DST_LPORT_IPS: "{{CNI.KUBEOVN.helm_values.func.LS_CT_SKIP_DST_LPORT_IPS}}"
            ENABLE_BIND_LOCAL_IP: "{{CNI.KUBEOVN.helm_values.func.ENABLE_BIND_LOCAL_IP}}"
            U2O_INTERCONNECTION: "{{CNI.KUBEOVN.helm_values.func.U2O_INTERCONNECTION}}"
            ENABLE_TPROXY: "{{CNI.KUBEOVN.helm_values.func.ENABLE_TPROXY}}"
            ENABLE_IC: "{{CNI.KUBEOVN.helm_values.func.ENABLE_IC}}"
          ipv4:
            POD_CIDR: "{{CNI.KUBEOVN.helm_values.ipv4.POD_CIDR}}"
            POD_GATEWAY: "{{CNI.KUBEOVN.helm_values.ipv4.POD_GATEWAY}}"
            SVC_CIDR: "{{CNI.KUBEOVN.helm_values.ipv4.SVC_CIDR}}"
            JOIN_CIDR: "{{CNI.KUBEOVN.helm_values.ipv4.JOIN_CIDR}}"
            PINGER_EXTERNAL_ADDRESS: "{{CNI.KUBEOVN.helm_values.ipv4.PINGER_EXTERNAL_ADDRESS}}"
            PINGER_EXTERNAL_DOMAIN: "{{CNI.KUBEOVN.helm_values.ipv4.PINGER_EXTERNAL_DOMAIN}}"
          networking:
            # NET_STACK could be dual_stack, ipv4, ipv6
            NET_STACK: ipv4
            ENABLE_SSL: false
            # network type could be geneve or vlan
            NETWORK_TYPE: geneve
            # tunnel type could be geneve, vxlan or stt
            TUNNEL_TYPE: geneve
            IFACE: ""
            DPDK_TUNNEL_IFACE: "br-phy"
            EXCLUDE_IPS: ""
            POD_NIC_TYPE: "veth-pair"
            vlan:
              PROVIDER_NAME: "provider"
              VLAN_INTERFACE_NAME: ""
              VLAN_NAME: "ovn-vlan"
              VLAN_ID: "100"
            ENABLE_EIP_SNAT: true
            EXCHANGE_LINK_NAME: false
            DEFAULT_SUBNET: "ovn-default"
            DEFAULT_VPC: "ovn-cluster"
            NODE_SUBNET: "join"
            ENABLE_ECMP: false
            ENABLE_METRICS: true
            NODE_LOCAL_DNS_IP: ""
            PROBE_INTERVAL: 180000
            OVN_NORTHD_PROBE_INTERVAL: 5000
            OVN_LEADER_PROBE_INTERVAL: 5
            OVN_REMOTE_PROBE_INTERVAL: 10000
            OVN_REMOTE_OPENFLOW_INTERVAL: 180
            OVN_NORTHD_N_THREADS: 1
            ENABLE_COMPACT: false

    - name: Sleep 90 second, init CNI KUBE OVN
      pause:
        seconds: 90
