    - name: Deploy CNI Calico
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      community.kubernetes.helm:
        name: cni-calico
        chart_ref: "cloudstack/tigera-operator"
        release_state: present
        update_repo_cache: true
        release_namespace: "{{CNI_CALICO_namespace}}"
        create_namespace: yes
        chart_version: "{{CNI_CALICO_VERSION}}"
        values:
          installation:
            enabled: true
            registry: "{{CNI_CALICO_registry}}"
            calicoNetwork:
              linuxDataplane: Iptables
              #    // +kubebuilder:validation:Enum=Iptables;BPF;VPP
              bgp: Disabled
              # Note: The ipPools section cannot be modified post-install.
              ipPools:
              - blockSize: "{{CNI_CALICO_BLOCKSIZE}}"
                cidr: "{{CNI_CALICO_CIDR}}"
                #     // +kubebuilder:validation:Enum=IPIPCrossSubnet;IPIP;VXLAN;VXLANCrossSubnet;None
                encapsulation: VXLANCrossSubnet
                natOutgoing: Enabled
                nodeSelector: all()
              nodeAddressAutodetectionV4:
                interface: "{{CNI_CALICO_INTERFACE}}"
          apiServer:
            enabled: true
          tolerations:
          - effect: NoExecute
            operator: Exists
          - effect: NoSchedule
            operator: Exists
          nodeSelector:
            kubernetes.io/os: linux
          tigeraOperator:
            image: "{{CNI_CALICO_tigeraOperator_image}}"
            version: "{{CNI_CALICO_otigeraOperator_version}}"
            registry: "{{CNI_CALICO_tigeraOperator_registry}}"
          calicoctl:
            image: "{{CNI_CALICO_ctl_image}}"
            tag: "{{CNI_CALICO_ctl_tag}}"
          kubeletVolumePluginPath: /var/lib/kubelet

    - name: Sleep 90 second, init CNI
      pause:
        seconds: 90

