
    - name: "Run - kubectl label node -lbeta.kubernetes.io/os=linux kubernetes.io/os=linux --overwrite"
      ansible.builtin.shell: kubectl label node -lbeta.kubernetes.io/os=linux kubernetes.io/os=linux --overwrite
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: "Run - kubectl label node -lnode-role.kubernetes.io/control-plane kube-ovn/role=master --overwrite"
      ansible.builtin.shell: kubectl label node -lnode-role.kubernetes.io/control-plane kube-ovn/role=master --overwrite
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: "Run - kubectl label node -lovn.kubernetes.io/ovs_dp_type!=userspace ovn.kubernetes.io/ovs_dp_type=kernel --overwrite"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      ansible.builtin.shell: kubectl label node -lovn.kubernetes.io/ovs_dp_type!=userspace ovn.kubernetes.io/ovs_dp_type=kernel --overwrite
      args:
        executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Deploy CNI KUBE-OVN
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      community.kubernetes.helm:
        name: kube-ovn
        chart_ref: "cloudstack/kube-ovn"
        release_state: present
        update_repo_cache: true
        release_namespace: default
        # kube-system
        create_namespace: no
        chart_version: v1.12.11
        values:
          global:
            registry:
              address: harbor.iblog.pro/dockerio/kubeovn
            images:
              kubeovn:
                repository: kube-ovn
                dpdkRepository: kube-ovn-dpdk
                vpcRepository: vpc-nat-gateway
                tag: v1.12.11
                support_arm: true
                thirdparty: true
          replicaCount: 3
          MASTER_NODES: "{{CNI.KUBEOVN.MASTERS}}"
          func:
            ENABLE_LB: true
            ENABLE_NP: true
            ENABLE_EXTERNAL_VPC: true
            HW_OFFLOAD: false
            ENABLE_LB_SVC: false
            ENABLE_KEEP_VM_IP: true
            LS_DNAT_MOD_DL_DST: true
            LS_CT_SKIP_DST_LPORT_IPS: true
            ENABLE_BIND_LOCAL_IP: true
            U2O_INTERCONNECTION: false
            ENABLE_TPROXY: false
            ENABLE_IC: false
          ipv4:
            POD_CIDR: "10.96.0.0/17"
            POD_GATEWAY: "10.96.0.1"
            SVC_CIDR: "10.96.128.0/17"
            JOIN_CIDR: "100.64.0.0/16"
            PINGER_EXTERNAL_ADDRESS: "192.168.200.1"
            PINGER_EXTERNAL_DOMAIN: "node1.cloud.local."
          networking:
            # NET_STACK could be dual_stack, ipv4, ipv6
            NET_STACK: ipv4
            ENABLE_SSL: false
            # network type could be geneve or vlan
            NETWORK_TYPE: geneve
            # tunnel type could be geneve, vxlan or stt
            TUNNEL_TYPE: geneve
            IFACE: ""
            DPDK_TUNNEL_IFACE: "br-phy"
            EXCLUDE_IPS: ""
            POD_NIC_TYPE: "veth-pair"
            vlan:
              PROVIDER_NAME: "provider"
              VLAN_INTERFACE_NAME: ""
              VLAN_NAME: "ovn-vlan"
              VLAN_ID: "100"
            ENABLE_EIP_SNAT: true
            EXCHANGE_LINK_NAME: false
            DEFAULT_SUBNET: "ovn-default"
            DEFAULT_VPC: "ovn-cluster"
            NODE_SUBNET: "join"
            ENABLE_ECMP: false
            ENABLE_METRICS: true
            NODE_LOCAL_DNS_IP: ""
            PROBE_INTERVAL: 180000
            OVN_NORTHD_PROBE_INTERVAL: 5000
            OVN_LEADER_PROBE_INTERVAL: 5
            OVN_REMOTE_PROBE_INTERVAL: 10000
            OVN_REMOTE_OPENFLOW_INTERVAL: 180
            OVN_NORTHD_N_THREADS: 1
            ENABLE_COMPACT: false
