

    - name: Copy istioctl
      ansible.builtin.copy:
        src: "UTILS/{{ISTIOCTL_FILE}}"
        dest: "/tmp/{{ISTIOCTL_FILE}}"
        owner: root
        group: root
        mode: '0644'

    - name: install istioctl
      environment:
        ISTIOCTL_VERSION: "{{ISTIOCTL_VERSION}}"
        ISTIOCTL_FILE: "{{ISTIOCTL_FILE}}"
      ansible.builtin.shell: |
              cd /tmp
              ls -la
              tar zxvfC {{ISTIOCTL_FILE}} /usr/bin/
              chmod +x /usr/bin/istioctl
      register: result
    - debug: var=result.stdout_lines

    - name: Run copy istio-operator.yaml.j2 /etc/kubernetes/istio-operator.yaml
      template:
        src: "istio-operator.yaml.j2"
        dest: /etc/kubernetes/istio-operator.yaml
        mode: '0600'
      register: logs
    - debug: var=logs.stdout_lines

    - name: Create a k8s namespace istio-ingressgateway-system
      kubernetes.core.k8s:
        name: istio-ingressgateway-system
        api_version: v1
        kind: Namespace
        state: present

    - name: Create a k8s namespace istio-ingressgateway-private
      kubernetes.core.k8s:
        name: istio-ingressgateway-private
        api_version: v1
        kind: Namespace
        state: present

    - name: Create a k8s namespace istio-ingressgateway-public
      kubernetes.core.k8s:
        name: istio-ingressgateway-public
        api_version: v1
        kind: Namespace
        state: present

    - name: Run istioctl manifest generate -f /etc/kubernetes/istio-operator.yaml > /etc/kubernetes/istio-manifest-full.yaml
      ansible.builtin.shell: cd /root; istioctl manifest generate -f /etc/kubernetes/istio-operator.yaml > /etc/kubernetes/istio-manifest-full.yaml
      args:
         executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Run istioctl manifest generate install -f /etc/kubernetes/istio-operator.yaml
      ansible.builtin.shell: cd /root; istioctl manifest install -f /etc/kubernetes/istio-operator.yaml -y
      args:
         executable: /bin/bash
      register: logs
    - debug: var=logs.stdout_lines

    - name: Sleep 60 second, Deploy ISTIO
      pause:
        seconds: 60
