    - name: Deploy ISTIO
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      community.kubernetes.helm:
        name: cloudstack-istio-system
        chart_ref: "cloudstack/istio-operator"
        release_state: present
        update_repo_cache: true
        release_namespace: "istio-system"
        create_namespace: yes
        chart_version: "1.23.3"
        values:
            # Global settings
            defaults:
              hub: harbor.iblog.pro/docker.io/istio
              tag: 1.23.3
              pilot:
                autoscaleEnabled: true
                autoscaleMin: 2
                autoscaleMax: 5
                autoscaleBehavior: {}
                replicaCount: 2
                rollingMaxSurge: 100%
                rollingMaxUnavailable: 25%

            image:
              repository: harbor.iblog.pro/ghcrio/banzaicloud/istio-operator
              tag: "v2.17.4"
            prometheusMetrics:
              authProxy:
                image:
                  repository: harbor.iblog.pro/gcrio/kubebuilder/kube-rbac-proxy
                  tag: "v0.8.0"

