
    - name: Deploy NFS Helm
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      community.kubernetes.helm:
        name: csi-driver-nfs
        chart_ref: "{{CSI.NFS_HELM.chart_ref}}"
        release_state: present
        update_repo_cache: true
        release_namespace: "{{CSI.NFS_HELM.release_namespace}}"
        create_namespace: "{{CSI.NFS_HELM.create_namespace}}"
        chart_version: "{{CSI.NFS_HELM.chart_version}}"
        values:
          controller:
            name: csi-nfs-controller
            replicas: 2
            resources:
              csiProvisioner:
                limits:
                  cpu: 100m
                  memory: 400Mi
                requests:
                  cpu: 10m
                  memory: 20Mi
              csiSnapshotter:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 10m
                  memory: 20Mi
              livenessProbe:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 10m
                  memory: 20Mi
              nfs:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 10m
                  memory: 20Mi
          node:
            resources:
              livenessProbe:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 10m
                  memory: 20Mi
              nodeDriverRegistrar:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 10m
                  memory: 20Mi
              nfs:
                limits:
                  cpu: 100m
                  memory: 300Mi
                requests:
                  cpu: 10m
                  memory: 20Mi
          image:
              baseRepo: "{{CSI.NFS_HELM.helm_values.image.baseRepo}}"
              nfs:
                  repository: "{{CSI.NFS_HELM.helm_values.image.nfs.repository}}"
                  tag: "{{CSI.NFS_HELM.helm_values.image.nfs.tag}}"
                  pullPolicy: "{{CSI.NFS_HELM.helm_values.image.nfs.pullPolicy}}"
              csiProvisioner:
                  repository: "{{CSI.NFS_HELM.helm_values.image.csiProvisioner.repository}}"
                  tag: "{{CSI.NFS_HELM.helm_values.image.csiProvisioner.tag}}"
                  pullPolicy: "{{CSI.NFS_HELM.helm_values.image.csiProvisioner.pullPolicy}}"
              csiSnapshotter:
                  repository: "{{CSI.NFS_HELM.helm_values.image.csiSnapshotter.repository}}"
                  tag: "{{CSI.NFS_HELM.helm_values.image.csiSnapshotter.tag}}"
                  pullPolicy: "{{CSI.NFS_HELM.helm_values.image.csiSnapshotter.pullPolicy}}"
              livenessProbe:
                  repository: "{{CSI.NFS_HELM.helm_values.image.livenessProbe.repository}}"
                  tag: "{{CSI.NFS_HELM.helm_values.image.livenessProbe.tag}}"
                  pullPolicy: "{{CSI.NFS_HELM.helm_values.image.livenessProbe.pullPolicy}}"
              nodeDriverRegistrar:
                  repository: "{{CSI.NFS_HELM.helm_values.image.nodeDriverRegistrar.repository}}"
                  tag: "{{CSI.NFS_HELM.helm_values.image.nodeDriverRegistrar.tag}}"
                  pullPolicy: "{{CSI.NFS_HELM.helm_values.image.nodeDriverRegistrar.pullPolicy}}"
              externalSnapshotter:
                  repository: "{{CSI.NFS_HELM.helm_values.image.externalSnapshotter.repository}}"
                  tag: "{{CSI.NFS_HELM.helm_values.image.externalSnapshotter.tag}}"
                  pullPolicy: "{{CSI.NFS_HELM.helm_values.image.externalSnapshotter.pullPolicy}}"

    - name: Sleep 60 second, init NFS HELM
      pause:
        seconds: 60

    - name: Create NFS HELM StorageClass
      kubernetes.core.k8s:
        state: present
        apply: true
        template:
          path: 'CSI-NFS-HELM/StorageClass.yaml.j2'

