
    - name: Deploy NFS Helm
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      community.kubernetes.helm:
        name: csi-driver-nfs
        chart_ref: "cloudstack/csi-driver-nfs"
        release_state: present
        update_repo_cache: true
        release_namespace: csi-driver-nfs
        create_namespace: yes
        chart_version: "v4.6.0"
        values:
          image:
              baseRepo: harbor.iblog.pro/registryk8sio
              nfs:
                  repository: harbor.iblog.pro/registryk8sio/sig-storage/nfsplugin
                  tag: v4.6.0
                  pullPolicy: IfNotPresent
              csiProvisioner:
                  repository: harbor.iblog.pro/registryk8sio/sig-storage/csi-provisioner
                  tag: v4.0.0
                  pullPolicy: IfNotPresent
              csiSnapshotter:
                  repository: harbor.iblog.pro/registryk8sio/sig-storage/csi-snapshotter
                  tag: v6.3.3
                  pullPolicy: IfNotPresent
              livenessProbe:
                  repository: harbor.iblog.pro/registryk8sio/sig-storage/livenessprobe
                  tag: v2.12.0
                  pullPolicy: IfNotPresent
              nodeDriverRegistrar:
                  repository: harbor.iblog.pro/registryk8sio/sig-storage/csi-node-driver-registrar
                  tag: v2.10.0
                  pullPolicy: IfNotPresent
              externalSnapshotter:
                  repository: harbor.iblog.pro/registryk8sio/sig-storage/snapshot-controller
                  tag: v6.3.3
                  pullPolicy: IfNotPresent

    - name: Sleep 60 second, init CNI
      pause:
        seconds: 60

    - name: Create NFS HELM StorageClass
      kubernetes.core.k8s:
        state: present
        apply: true
        template:
          path: 'CSI-NFS-HELM/StorageClass.yaml.j2'

