    - name: Deploy cilium w/o cluster mesh
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      community.kubernetes.helm:
        name: cloudstack-cilium
        chart_ref: "{{CNI.CILIUM.chart_ref}}"
        release_state: "{{CNI.CILIUM.release_state}}"
        update_repo_cache: "{{CNI.CILIUM.update_repo_cache}}"
        release_namespace: "{{CNI.CILIUM.release_namespace}}"
        create_namespace: "{{CNI.CILIUM.create_namespace}}"
        chart_version: "{{CNI.CILIUM.chart_version}}"
        values:
          kubeProxyReplacement: "{{CNI.CILIUM.cilium_kubeProxyReplacement}}"
          clusterDomain: "KUBERNETES_clusterDomain"
          k8sServiceHost: "{{KUBERNETES_VIP}}"
          k8sServicePort: 6443
          rollOutCiliumPods: true
          tunnelProtocol: "{{CNI.CILIUM.cilium_tunnelProtocol}}"
          routingMode: "{{CNI.CILIUM.cilium_routingMode}}"
          l7Proxy: "{{CNI.CILIUM.cilium_l7Proxy}}"
          localRedirectPolicy: false
          # https://docs.cilium.io/en/stable/network/kubernetes/bandwidth-manager/
          bandwidthManager:
            enabled: true
          bpf:
            masquerade: true
          # https://docs.cilium.io/en/stable/network/servicemesh/ingress/#installation
          ingressController:
            enabled: "{{CNI.CILIUM.cilium_ingressController}}"
            loadbalancerMode: "{{CNI.CILIUM.cilium_ingressController_loadbalancerMode}}"
          cni:
            exclusive: false
          hostFirewall:
            enabled: false
          ipv4:
            # -- Enable IPv4 support.
            enabled: true
          ipv6:
            # -- Enable IPv6 support.
            enabled: false
          ipMasqAgent:
            enabled: false
 #         ipv4NativeRoutingCIDR: "192.168.200.0/24"
          ipv4NativeRoutingCIDR: ""
          ipv6NativeRoutingCIDR: ""
          hostPort:
            enabled: false
          socketLB:
            enabled: false
          bgp:
            enabled: false
          bgpControlPlane:
            enabled: true
          nodePort:
            enabled: "{{CNI.CILIUM.cilium_nodePort}}"
          egressGateway:
              enabled: "{{CNI.CILIUM.cilium_egressGateway}}"
          preflight:
              image:
                  repository: "harbor.iblog.pro/quayio/cilium/cilium"
                  digest: ""
                  useDigest: false
          ipam:
              operator:
                  clusterPoolIPv4PodCIDRList: "{{CNI.CILIUM.clusterPoolIPv4PodCIDRList}}"
#                  clusterPoolIPv4MaskSize: "{{CNI.CILIUM.clusterPoolIPv4MaskSize}}"
#                  clusterPoolIPv4MaskSize: "{{CNI.CILIUM.clusterPoolIPv4MaskSize}}"
# fatal: [node130]: FAILED! => {"changed": false, "command": "/usr/bin/helm --version=1.16.1 upgrade -i --reset-values --create-namespace -f=/tmp/tmp34z_scqh.yml cloudstack-cilium cloudstack/cilium", "msg": "Failure when executing Helm >
          debug:
            enabled: true
          monitor:
            enabled: false
          image:
            repository: "{{CNI.CILIUM.cilium_repository}}"
            digest: ""
            useDigest: false
          certgen:
            image:
              repository: "{{CNI.CILIUM.certgen_repository}}"
              digest: ""
              useDigest: false
          resources:
             limits:
               cpu: 1000m
               memory: 1Gi
             requests:
               cpu: 100m
               memory: 512Mi
          hubble:
            enabled: "{{CNI.CILIUM.cilium_hubble}}"
            relay:
              enabled: "{{CNI.CILIUM.cilium_hubble_relay}}"
              image:
                repository: "{{CNI.CILIUM.hubble_relay_repository}}"
                digest: ""
                useDigest: false
              resources:
                 limits:
                   cpu: 250m
                   memory: 256Mi
                 requests:
                   cpu: 100m
                   memory: 128Mi
              replicas: 2
            ui:
              enabled: "{{CNI.CILIUM.cilium_hubble_ui}}"
              frontend:
                image:
                  repository: "{{CNI.CILIUM.hubble_ui_repository}}"
                  digest: ""
                  useDigest: false
                resources:
                   limits:
                     cpu: 300m
                     memory: 256Mi
                   requests:
                     cpu: 100m
                     memory: 128Mi
              backend:
                image:
                  repository: "{{CNI.CILIUM.hubble_ui_backend_repository}}"
                  digest: ""
                  useDigest: false
                resources:
                   limits:
                     cpu: 300m
                     memory: 256Mi
                   requests:
                     cpu: 100m
                     memory: 128Mi
          etcd:
            enabled: false
            image:
              repository: "{{CNI.CILIUM.cilium_etcd_operator_repository}}"
              digest: ""
              useDigest: false
          operator:
            enabled: true
            rollOutPods: true
            image:
              repository: "{{CNI.CILIUM.operator_repository}}"
              digest: ""
              useDigest: false
            podDisruptionBudget:
              enabled: true
#              minAvailable: 1
#              maxUnavailable: 1
            resources:
               limits:
                 cpu: 1000m
                 memory: 1Gi
               requests:
                 cpu: 100m
                 memory: 128Mi
          nodeinit:
            enabled: false
            image:
              repository: "{{CNI.CILIUM.startup_script_repository}}"
              digest: ""
              useDigest: false
            resources:
              requests:
                 cpu: 100m
                 memory: 100Mi
              limits:
                 cpu: 1000m
                 memory: 1Gi
          loadBalancer:
            l7:
              backend: "envoy"
          envoy:
            enabled: "{{CNI.CILIUM.cilium_envoy}}"
            image:
              repository: "{{CNI.CILIUM.cilium_envoy_repository}}"
              digest: ""
              useDigest: false
            resources:
               limits:
                 cpu: 1000m #4000m
                 memory: 1Gi #4Gi
               requests:
                 cpu: 100m
                 memory: 512Mi
          clustermesh:
            useAPIServer: false
            apiserver:
              image:
                repository: "{{CNI.CILIUM.clustermesh_apiserver_repository}}"
                digest: ""
                useDigest: false
            mutual:
              spire:
                enabled: false
                install:
                  enabled: true
                  namespace: cilium-spire
                  existingNamespace: false
                  initImage:
                    repository: "{{CNI.CILIUM.busybox_repository}}"
                    digest: ""
                    useDigest: false
                  agent:
                    image:
                      repository: "{{CNI.CILIUM.spire_agent_repository}}"
                      digest: ""
                      useDigest: false
                  server:
                    image:
                      repository: "{{CNI.CILIUM.spire_server_repository}}"
                      digest: ""
                      useDigest: false
      register: result

    - debug: var=result.stdout_lines

    - name: Sleep 120 second, init CNI
      pause:
        seconds: 120

