
    - name: Create PriorityClass
      kubernetes.core.k8s:
        state: present
        apply: true
        template:
          path: 'POST-INIT/PriorityClass.yaml.j2'

    - name: Create RuntimeClass gVisor
      kubernetes.core.k8s:
        state: present
        definition:
      kubernetes.core.k8s:
        state: present
        apply: true
        definition:
            apiVersion: node.k8s.io/v1
            kind: RuntimeClass
            metadata:
              name: gvisor
            handler: runsc


