apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 11.0.0.0-11.0.3.255
    - name: internet
      protocol: layer2
      addresses:
      - 11.0.10.1-11.0.10.1
    - name: internet2
      protocol: layer2
      addresses:
      - 11.0.11.2-11.0.11.2
    - name: coredns-kube
      protocol: layer2
      addresses:
      - 11.0.11.22-11.0.11.22
