CNI:
    ANTREA:
        chart_ref: "{{CNI_ANTREA_chart_ref}}"
        release_state: "{{CNI_ANTREA_release_state}}"
        update_repo_cache: true
        release_namespace: "{{CNI_ANTREA_release_namespace}}"
        create_namespace: "{{CNI_ANTREA_create_namespace}}"
        chart_version: "{{CNI_ANTREA_chart_version}}"
        helm_values:
          agentImage:
            repository: "{{CNI_ANTREA_agentImage_repository}}"
            pullPolicy: "{{CNI_ANTREA_agentImage_pullPolicy}}"
            tag: "{{CNI_ANTREA_agentImage_tag}}"
          controllerImage:
            repository: "{{CNI_ANTREA_controllerImage_repository}}"
            pullPolicy: "{{CNI_ANTREA_controllerImage_pullPolicy}}"
            tag: "{{CNI_ANTREA_controllerImage_tag}}"

    KUBEOVN:
        MASTERS: "{{CNI_KUBEOVN_MASTERS}}"
        chart_ref: "{{CNI_KUBEOVN_chart_ref}}"
        release_state: "{{CNI_KUBEOVN_release_state}}"
        update_repo_cache: true
        release_namespace: "{{CNI_KUBEOVN_release_namespace}}"
        create_namespace: "{{CNI_KUBEOVN_create_namespace}}"
        chart_version: "{{CNI_KUBEOVN_chart_version}}"
        helm_values:
          global:
            registry:
              address: "{{CNI_KUBEOVN_chart_global_registry}}"
            images:
              kubeovn:
                repository: "{{CNI_KUBEOVN_chart_kubeovn_repository}}"
                dpdkRepository: "{{CNI_KUBEOVN_chart_kubeovn_dpdkRepository}}"
                vpcRepository: "{{CNI_KUBEOVN_chart_kubeovn_vpcRepository}}"
                tag: "{{CNI_KUBEOVN_chart_kubeovn_tag}}"
                support_arm: true
                thirdparty: true
          func:
            ENABLE_LB: "{{CNI_KUBEOVN_func_ENABLE_LB}}"
            ENABLE_NP: "{{CNI_KUBEOVN_func_ENABLE_NP}}"
            ENABLE_EXTERNAL_VPC: "{{CNI_KUBEOVN_func_ENABLE_EXTERNAL_VPC}}"
            HW_OFFLOAD: "{{CNI_KUBEOVN_func_HW_OFFLOAD}}"
            ENABLE_LB_SVC: "{{CNI_KUBEOVN_func_ENABLE_LB_SVC}}"
            ENABLE_KEEP_VM_IP: "{{CNI_KUBEOVN_func_ENABLE_KEEP_VM_IP}}"
            LS_DNAT_MOD_DL_DST: "{{CNI_KUBEOVN_func_LS_DNAT_MOD_DL_DST}}"
            LS_CT_SKIP_DST_LPORT_IPS: "{{CNI_KUBEOVN_func_LS_CT_SKIP_DST_LPORT_IPS}}"
            ENABLE_BIND_LOCAL_IP: "{{CNI_KUBEOVN_func_ENABLE_BIND_LOCAL_IP}}"
            U2O_INTERCONNECTION: "{{CNI_KUBEOVN_func_U2O_INTERCONNECTION}}"
            ENABLE_TPROXY: "{{CNI_KUBEOVN_func_ENABLE_TPROXY}}"
            ENABLE_IC: "{{CNI_KUBEOVN_func_ENABLE_IC}}"
          ipv4:
            POD_CIDR: "{{CNI_KUBEOVN_ipv4_POD_CIDR}}"
            POD_GATEWAY: "{{CNI_KUBEOVN_ipv4_POD_GATEWAY}}"
            SVC_CIDR: "{{CNI_KUBEOVN_ipv4_SVC_CIDR}}"
            JOIN_CIDR: "{{CNI_KUBEOVN_ipv4_JOIN_CIDR}}"
            PINGER_EXTERNAL_ADDRESS: "{{CNI_KUBEOVN_ipv4_PINGER_EXTERNAL_ADDRESS}}"
            PINGER_EXTERNAL_DOMAIN: "{{CNI_KUBEOVN_ipv4_PINGER_EXTERNAL_DOMAIN}}"

    CILIUM:
        chart_ref: "{{CNI_CILIUM_chart_ref}}"
        release_state: "{{CNI_CILIUM_release_state}}"
        update_repo_cache: true
        release_namespace: "{{CNI_CILIUM_release_namespace}}"
        create_namespace: "{{CNI_CILIUM_create_namespace}}"
        chart_version: "{{CNI_CILIUM_chart_version}}"

        clusterPoolIPv4PodCIDRList: "{{CNI_CILIUM_clusterPoolIPv4PodCIDRList}}"
        clusterPoolIPv4MaskSize: "{{CNI_CILIUM_clusterPoolIPv4MaskSize}}"

        cilium_repository: "{{CNI_CILIUM_cilium_repository}}"
        certgen_repository: "{{CNI_CILIUM_certgen_repository}}"
        hubble_relay_repository: "{{CNI_CILIUM_hubble_relay_repository}}"
        hubble_ui_backend_repository: "{{CNI_CILIUM_hubble_ui_backend_repository}}"
        hubble_ui_repository: "{{CNI_CILIUM_hubble_ui_repository}}"
        cilium_envoy_repository: "{{CNI_CILIUM_cilium_envoy_repository}}"
        cilium_etcd_operator_repository: "{{CNI_CILIUM_cilium_etcd_operator_repository}}"
        operator_repository: "{{CNI_CILIUM_operator_repository}}"
        startup_script_repository: "{{CNI_CILIUM_startup_script_repository}}"
        clustermesh_apiserver_repository: "{{CNI_CILIUM_clustermesh_apiserver_repository}}"
        busybox_repository: "{{CNI_CILIUM_busybox_repository}}"
        spire_agent_repository: "{{CNI_CILIUM_spire_agent_repository}}"
        spire_server_repository: "{{CNI_CILIUM_spire_server_repository}}"

        cilium_tunnelProtocol: "vxlan"
        cilium_l7Proxy: true
        cilium_ingressController: true
        cilium_ingressController_loadbalancerMode: "dedicated"

        cilium_nodePort: true
        cilium_egressGateway: true
        # cilium_kubeProxyReplacement: strict
        cilium_kubeProxyReplacement: true

        cilium_hubble: false
        cilium_hubble_relay: false
        cilium_hubble_ui: false

        cilium_envoy: true
        cilium_envoy_repository: "harbor.iblog.pro/quayio/cilium/cilium-envoy"

        # cilium_loadBalancer_l7_backend: "envoy"
        cilium_loadBalancer_l7_backend: "disabled"


    METALLB:
        chart_version: "{{CNI_METALLB_chart_version}}"
        prometheus_repository: "{{CNI_METALLB_prometheus_repository}}"
        prometheus_tag: "{{CNI_METALLB_prometheus_tag}}"
        controller_repository: "{{CNI_METALLB_controller_repository}}"
        controller_tag: "{{CNI_METALLB_controller_tag}}"
        speaker_repository: "{{CNI_METALLB_speaker_repository}}"
        speaker_tag: "{{CNI_METALLB_speaker_tag}}"
        frr_repository: "{{CNI_METALLB_frr_repository}}"
        frr_tag: "{{CNI_METALLB_frr_tag}}"
        ippools:
          default:
          - "{{ METALLB_BLOCK1 }}"
          internet:
          - "{{ METALLB_BLOCK2 }}"
          internet2:
          - "{{ METALLB_BLOCK3 }}"
          coredns-kube:
          - "{{ METALLB_BLOCK4 }}"



