CSI:
    NFS:
        NAMESPACE: nfs-client
        image: harbor.iblog.pro/gcrio/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.2
        PROVISIONER_NAME: iblog.pro/nfs
        SERVER: 192.168.200.1
        SERVER_path: /cloud/nfsshare
        replicas: 2

    NFS_HELM:
        chart_ref: "cloudstack/csi-driver-nfs"
        release_namespace: csi-driver-nfs
        create_namespace: yes
        chart_version: "v4.6.0"
        helm_values:
          image:
              baseRepo: harbor.iblog.pro/registry.k8s.io
              nfs:
                  repository: harbor.iblog.pro/registry.k8s.io/sig-storage/nfsplugin
                  tag: v4.6.0
                  pullPolicy: IfNotPresent
              csiProvisioner:
                  repository: harbor.iblog.pro/registry.k8s.io/sig-storage/csi-provisioner
                  tag: v4.0.0
                  pullPolicy: IfNotPresent
              csiSnapshotter:
                  repository: harbor.iblog.pro/registry.k8s.io/sig-storage/csi-snapshotter
                  tag: v6.3.3
                  pullPolicy: IfNotPresent
              livenessProbe:
                  repository: harbor.iblog.pro/registry.k8s.io/sig-storage/livenessprobe
                  tag: v2.12.0
                  pullPolicy: IfNotPresent
              nodeDriverRegistrar:
                  repository: harbor.iblog.pro/registry.k8s.io/sig-storage/csi-node-driver-registrar
                  tag: v2.10.0
                  pullPolicy: IfNotPresent
              externalSnapshotter:
                  repository: harbor.iblog.pro/registry.k8s.io/sig-storage/snapshot-controller
                  tag: v6.3.3
                  pullPolicy: IfNotPresent

