INGRESS:
    NGINX:
        chart_ref: "cloudstack/ingress-nginx"
        release_state: present
        update_repo_cache: true
        create_namespace: yes
        chart_version: "4.10.4"
        controller_registry: registry.k8s.io
        controller_image: ingress-nginx/controller
        controller_tag: "v1.10.4"
        controller_digest: sha256:505b9048c02dde3d6c8667bf0b52aba7b36adf7b03da34c47d5fa312d2d4c6fc
        controller_digestChroot: sha256:bf71acf6e71830a4470e2183e3bc93c4f006b954f8a05fb434242ef0f8a24858
        INGRESS_IPPOOL: default
        INGRESS_pools:
          ingress-nginx-1:
          - "{{ INGRESS_BLOCK1 }}"
          ingress-nginx-2:
          - "{{ INGRESS_BLOCK2 }}"
          system-ingress:
          - "{{ INGRESS_BLOCK3 }}"
