INGRESS:
    NGINX:
        chart_ref: "cloudstack/ingress-nginx"
        release_state: present
        update_repo_cache: true
        create_namespace: yes
        chart_version: "4.10.0"
        controller_registry: registry.k8s.io
        controller_image: ingress-nginx/controller
        controller_tag: "v1.10.0"
        controller_digest: sha256:42b3f0e5d0846876b1791cd3afeb5f1cbbe4259d6f35651dcc1b5c980925379c
        controller_digestChroot: sha256:7eb46ff733429e0e46892903c7394aff149ac6d284d92b3946f3baf7ff26a096
        INGRESS_IPPOOL: default
        INGRESS_pools:
          ingress-nginx-1:
          - "{{ INGRESS_BLOCK1 }}"
          ingress-nginx-2:
          - "{{ INGRESS_BLOCK2 }}"
          system-ingress:
          - "{{ INGRESS_BLOCK3 }}"
