
HELMVERSION: "3.15.2"
platform: "amd64"
#KUBERNETES_VIP: "192.168.200.186"
KUBERNETES_clusterDomain: cluster.local
HELMFILE: "helm-v{{HELMVERSION}}-linux-{{platform}}.tar.gz"
HELM_CHARTMUSEUM_NAME: "cloudstack"
HELM_CHARTMUSEUM: "http://192.168.200.6:8080/"

TEST_HARBOR: harbor.iblog.pro/test/alpine:main.scratch.3.19.stage.4

KUBEADM_CONFIG_VERSION: "v114"

INIT_NODE_KUBERNETES: true
INIT_KUBERNETES: true
JOIN_WORKER_NODES_KUBERNETES: true
INIT_JOIN_MASTER_NODES_KUBERNETES: true
JOIN_MASTER_NODES_KUBERNETES: true
SEC_PATCH_KUBERNETES: true

#INIT_NODE_KUBERNETES: false
#INIT_KUBERNETES: false
#JOIN_WORKER_NODES_KUBERNETES: false
#INIT_JOIN_MASTER_NODES_KUBERNETES: false
#JOIN_MASTER_NODES_KUBERNETES: false



#DEPLOY_HELM: true
#DEPLOY_CSI_NFS: false
#DEPLOY_NFS_HELM: false

#DEPLOY_CSI_NFS: false
#DEPLOY_PriorityClass: false
#DEPLOY_METRICSERVER: false
#DEPLOY_CERMANAGER: false

#DEPLOY_CNI_CILIUM: false
#DEPLOY_CNI_ANTREA: false
#DEPLOY_CNI_KUBEOVN: false

#DEPLOY_METALLB: false
#DEPLOY_Nginx_Ingress: false

DEPLOY_HELM: true

DEPLOY_CSI_NFS: false
DEPLOY_NFS_HELM: true

DEPLOY_PriorityClass: true

DEPLOY_METRICSERVER: true
DEPLOY_CERMANAGER: true

DEPLOY_CNI_CILIUM: false
DEPLOY_CNI_ANTREA: false
DEPLOY_CNI_KUBEOVN: false
DEPLOY_CNI_CALICO: true

DEPLOY_METALLB: true
DEPLOY_Nginx_Ingress: true

KUBERNETES_VERSION: 1.31.1

kube_version: "v{{ KUBERNETES_VERSION }}"
crictl_version: "v1.31.1"
containerd_version: "1.7.22"
image_arch: "amd64"
runc_version: "1.1.13"
cni_version: "1.5.1"
k8s_regestry: "harbor.iblog.pro/registry.k8s.io"
etcd_version: "3.5.16"
LANG: ru_RU.UTF-8
#UBUNTU_VERSION: jammy
#noble
#DEBIAN_VERSION: bookworm
# VERSION: jammy
#NAMESERVER: "192.168.1.10"

#IPREFIX: "192.168.200"
#CLUSTERIP: "186"
#NODE: "180"
clusterName: "cluster.local"
#podSubnet: "10.96.0.0/17"
#serviceSubnet: "10.96.128.0/17"
APITOKEN: "bu5tiw.iq1i8h3t740fgy0l"

etcdquotaBackendBytes: "33554432000"

nodeMonitorPeriod:  "40s"
nodeMonitorGracePeriod: "5s"

#VIPIP_KEEPALIVE: "192.168.200.186"
APISERVER_DEST_PORT: 6443
keepalived_auth_type: AH
keepalived_auth_pass: "e470f1261"
KEEPALIVE_id: 51

kubernetesVersion: "{{ KUBERNETES_VERSION }}"
#CONTROL_PLANE_IP: 192.168.200.186



CNI_CALICO_VERSION: "v3.27.2"
CNI_CALICO_BLOCKSIZE: 26
CNI_CALICO_CIDR: "10.96.0.0/17"
CNI_CALICO_INTERFACE: "(enp1s0.800)"

CNI_CALICO_tigeraOperator_image: quayio/tigera/operator
CNI_CALICO_otigeraOperator_version: v1.32.5
CNI_CALICO_tigeraOperator_registry: harbor.iblog.pro
CNI_CALICO_ctl_image: harbor.iblog.pro/dockerio/calico/ctl
CNI_CALICO_ctl_tag: v3.27.2


CNI_METALLB_chart_version: "0.14.5"
CNI_METALLB_prometheus_repository: harbor.iblog.pro/gcrio/kubebuilder/kube-rbac-proxy
CNI_METALLB_prometheus_tag: "v0.12.0"
CNI_METALLB_controller_repository: harbor.iblog.pro/quayio/metallb/controller
CNI_METALLB_controller_tag: "v0.14.5"
CNI_METALLB_speaker_repository: harbor.iblog.pro/quayio/metallb/speaker
CNI_METALLB_speaker_tag: "v0.14.5"
CNI_METALLB_frr_repository: harbor.iblog.pro/quayio/frrouting/frr
CNI_METALLB_frr_tag: "9.0.2"


CNI_ANTREA_chart_ref: "cloudstack/antrea"
CNI_ANTREA_release_state: present
CNI_ANTREA_release_namespace: kube-system
CNI_ANTREA_create_namespace: no
CNI_ANTREA_chart_version: 2.0.0
CNI_ANTREA_agentImage_repository: "harbor.iblog.pro/dockerio/antrea/antrea-agent-ubuntu"
CNI_ANTREA_agentImage_pullPolicy: "IfNotPresent"
CNI_ANTREA_agentImage_tag: "v2.0.0"
CNI_ANTREA_controllerImage_repository: "harbor.iblog.pro/dockerio/antrea/antrea-controller-ubuntu"
CNI_ANTREA_controllerImage_pullPolicy: "IfNotPresent"
CNI_ANTREA_controllerImage_tag: "v2.0.0"



CNI_KUBEOVN_MASTERS: "192.168.200.180,192.168.200.181,192.168.200.182"
CNI_KUBEOVN_chart_ref: "cloudstack/kube-ovn"
CNI_KUBEOVN_release_state: present
CNI_KUBEOVN_release_namespace: kube-system
CNI_KUBEOVN_create_namespace: no

CNI_KUBEOVN_chart_version: "v1.12.16"
CNI_KUBEOVN_chart_global_registry: "harbor.iblog.pro/dockerio/kubeovn"

CNI_KUBEOVN_chart_kubeovn_repository: "kube-ovn"
CNI_KUBEOVN_chart_kubeovn_dpdkRepository: "kube-ovn-dpdk"
CNI_KUBEOVN_chart_kubeovn_vpcRepository: "vpc-nat-gateway"
CNI_KUBEOVN_chart_kubeovn_tag: "v1.12.16"

CNI_KUBEOVN_func_ENABLE_LB: true
CNI_KUBEOVN_func_ENABLE_NP: true
CNI_KUBEOVN_func_ENABLE_EXTERNAL_VPC: true
CNI_KUBEOVN_func_HW_OFFLOAD: false
CNI_KUBEOVN_func_ENABLE_LB_SVC: false
CNI_KUBEOVN_func_ENABLE_KEEP_VM_IP: true
CNI_KUBEOVN_func_LS_DNAT_MOD_DL_DST: true
CNI_KUBEOVN_func_LS_CT_SKIP_DST_LPORT_IPS: true
CNI_KUBEOVN_func_ENABLE_BIND_LOCAL_IP: true
CNI_KUBEOVN_func_U2O_INTERCONNECTION: false
CNI_KUBEOVN_func_ENABLE_TPROXY: false
CNI_KUBEOVN_func_ENABLE_IC: false

CNI_KUBEOVN_ipv4_POD_CIDR: "10.96.0.0/17"
CNI_KUBEOVN_ipv4_POD_GATEWAY: "10.96.0.1"
CNI_KUBEOVN_ipv4_SVC_CIDR: "10.96.128.0/17"
CNI_KUBEOVN_ipv4_JOIN_CIDR: "100.64.0.0/16"
CNI_KUBEOVN_ipv4_PINGER_EXTERNAL_ADDRESS: "192.168.200.1"
CNI_KUBEOVN_ipv4_PINGER_EXTERNAL_DOMAIN: "node1.cloud.local."


## VARS CILIUM

CNI_CILIUM_chart_ref: "cloudstack/cilium"
CNI_CILIUM_release_state: present
CNI_CILIUM_release_namespace: kube-system
CNI_CILIUM_create_namespace: yes
CNI_CILIUM_chart_version: 1.15.5

CNI_CILIUM_clusterPoolIPv4PodCIDRList: "10.97.0.0/17"
CNI_CILIUM_clusterPoolIPv4MaskSize: "24"

CNI_CILIUM_cilium_repository: "harbor.iblog.pro/quayio/cilium/cilium"
CNI_CILIUM_certgen_repository: "harbor.iblog.pro/quayio/cilium/certgen"
CNI_CILIUM_hubble_relay_repository: "harbor.iblog.pro/quayio/cilium/hubble-relay"
CNI_CILIUM_hubble_ui_backend_repository: "harbor.iblog.pro/quayio/cilium/hubble-ui-backend"
CNI_CILIUM_hubble_ui_repository: "harbor.iblog.pro/quayio/cilium/hubble-ui"
CNI_CILIUM_cilium_envoy_repository: "harbor.iblog.pro/quayio/cilium/cilium-envoy"
CNI_CILIUM_cilium_etcd_operator_repository: "harbor.iblog.pro/quayio/cilium/cilium-etcd-operator"
CNI_CILIUM_operator_repository: "harbor.iblog.pro/quayio/cilium/operator"
CNI_CILIUM_startup_script_repository: "harbor.iblog.pro/quayio/cilium/startup-script"
CNI_CILIUM_clustermesh_apiserver_repository: "harbor.iblog.pro/quayio/cilium/clustermesh-apiserver"
CNI_CILIUM_busybox_repository: "harbor.iblog.pro/dockerio/library/busybox"
CNI_CILIUM_spire_agent_repository: "harbor.iblog.pro/ghcrio/spiffe/spire-agent"
CNI_CILIUM_spire_server_repository: "harbor.iblog.pro/ghcrio/spiffe/spire-server"


## VARS CILIUM MULTICLASTER
CNI_CILIUM_MULTICLASTER_clusterDomain: cluster170
CNI_CILIUM_MULTICLASTER_nodeinit: enable
CNI_CILIUM_MULTICLASTER_localRedirectPolicy: false
CNI_CILIUM_MULTICLASTER_l7Proxy: false
CNI_CILIUM_MULTICLASTER_kubeProxyReplacement: partial
CNI_CILIUM_MULTICLASTER_hostServices: false
CNI_CILIUM_MULTICLASTER_externalIPs: true
CNI_CILIUM_MULTICLASTER_nodePort: true
CNI_CILIUM_MULTICLASTER_hostPort: true
CNI_CILIUM_MULTICLASTER_clustermesh_useAPIServer: true
CNI_CILIUM_MULTICLASTER_clustermesh_enabled: true
CNI_CILIUM_MULTICLASTER_clustermesh_domain: mesh.iblog.pro
CNI_CILIUM_MULTICLASTER_tunnel: geneve
CNI_CILIUM_MULTICLASTER_cluster_name: cluster170
CNI_CILIUM_MULTICLASTER_cluster_id: 170
CNI_CILIUM_MULTICLASTER_egressGateway: false
CNI_CILIUM_MULTICLASTER_hubble: false
CNI_CILIUM_MULTICLASTER_ingressController: false
CNI_CILIUM_MULTICLASTER_hubble_relay: false
CNI_CILIUM_MULTICLASTER_hubble_ui: false
CNI_CILIUM_MULTICLASTER_socketLB: true

CNI_CILIUM_MULTICLASTER: false
