
HELMVERSION: "3.14.3"
platform: "amd64"
#KUBERNETES_VIP: "192.168.200.186"
KUBERNETES_clusterDomain: cluster.local
HELMFILE: "helm-v{{HELMVERSION}}-linux-{{platform}}.tar.gz"
HELM_CHARTMUSEUM_NAME: "cloudstack"
HELM_CHARTMUSEUM: "http://192.168.200.6:8080/"

TEST_HARBOR: harbor.iblog.pro/test/alpine:main.scratch.3.19.stage.4

KUBEADM_CONFIG_VERSION: "v92"

INIT_NODE_KUBERNETES: true
INIT_KUBERNETES: true
JOIN_WORKER_NODES_KUBERNETES: true
INIT_JOIN_MASTER_NODES_KUBERNETES: true
JOIN_MASTER_NODES_KUBERNETES: true

#INIT_NODE_KUBERNETES: false
#INIT_KUBERNETES: false
#JOIN_WORKER_NODES_KUBERNETES: false
#INIT_JOIN_MASTER_NODES_KUBERNETES: false
#JOIN_MASTER_NODES_KUBERNETES: false



#DEPLOY_HELM: true
#DEPLOY_CSI_NFS: false
#DEPLOY_NFS_HELM: false

#DEPLOY_CSI_NFS: false
#DEPLOY_PriorityClass: false
#DEPLOY_METRICSERVER: false
#DEPLOY_CERMANAGER: false

#DEPLOY_CNI_CILIUM: false
#DEPLOY_CNI_ANTREA: false
#DEPLOY_CNI_KUBEOVN: false

#DEPLOY_METALLB: false
#DEPLOY_Nginx_Ingress: false

DEPLOY_HELM: true

DEPLOY_CSI_NFS: false
DEPLOY_NFS_HELM: true

DEPLOY_PriorityClass: true

DEPLOY_METRICSERVER: true
DEPLOY_CERMANAGER: true

DEPLOY_CNI_CILIUM: false
DEPLOY_CNI_ANTREA: false
DEPLOY_CNI_KUBEOVN: false
DEPLOY_CNI_CALICO: true

DEPLOY_METALLB: true
DEPLOY_Nginx_Ingress: true

KUBERNETES_VERSION: 1.30.0

kube_version: "v{{ KUBERNETES_VERSION }}"
crictl_version: "v1.29.0"
containerd_version: "1.7.16"
image_arch: "amd64"
runc_version: "1.1.12"
cni_version: "1.4.1"
k8s_regestry: "harbor.iblog.pro/registry.k8s.io"
etcd_version: "3.5.13"
LANG: ru_RU.UTF-8
#UBUNTU_VERSION: jammy
#noble
#DEBIAN_VERSION: bookworm
# VERSION: jammy
#NAMESERVER: "192.168.1.10"

#IPREFIX: "192.168.200"
#CLUSTERIP: "186"
#NODE: "180"
clusterName: "cluster.local"
#podSubnet: "10.96.0.0/17"
#serviceSubnet: "10.96.128.0/17"
APITOKEN: "bu5tiw.iq1i8h3t740fgy0l"

etcdquotaBackendBytes: "33554432"

nodeMonitorPeriod:  "40s"
nodeMonitorGracePeriod: "5s"

#VIPIP_KEEPALIVE: "192.168.200.186"
APISERVER_DEST_PORT: 6443
keepalived_auth_type: AH
keepalived_auth_pass: "e470f1261"
KEEPALIVE_id: 51

kubernetesVersion: "{{ KUBERNETES_VERSION }}"
#CONTROL_PLANE_IP: 192.168.200.186

