apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-main
  namespace: test-ingress-2
  labels:
    app: nginx-main
spec:
  selector:
    matchLabels:
      app: nginx-main
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: nginx-main
    spec:
      volumes:
      - name: webdata
        emptyDir: {}
      initContainers:
      - name: web-content
        image: docker.io/busybox
        volumeMounts:
        - name: webdata
          mountPath: "/webdata"
        command: ["/bin/sh", "-c", 'echo "<h1>I am <font color=green>MAIN</font></h1>" > /webdata/index.html']
      containers:
      - image: docker.io/nginx:1.19
        name: nginx-green2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: webdata
          mountPath: "/usr/share/nginx/html"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-main
  namespace: test-ingress-2
spec:
  selector:
    app: nginx-main
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 80
  type: NodePort

